### ISSUE TITLE
enable_cross_zone_load_balancing is not a valid argument

### ISSUE THREAD

**Issue by rastakajakwanna** [terraform-aws-modules/terraform-aws-alb#89] opened 2018-11-02 16:25 UTC
Module input "enable_cross_zone_load_balancing" is not a valid argument says Terraform. It seems to be too silly to be a bug, however I can run successfully `terraform plan` as soon as I comment out this input arg.

**To Reproduce**
```
module "alb" {
# add mandatory inputs
  enable_cross_zone_load_balancing = "true"
}
```
Terraform output:
```
Error: module "alb": "enable_cross_zone_load_balancing" is not a valid argument
```

**Expected behavior**
`terraform plan` will give usual output

**Desktop (please complete the following information):**
 - OS: Linux
 - Versions `Terraform v0.11.8` `provider.aws v1.41.0`

**Comment by edzillion** [comment] 2018-11-06 17:21
I think the problem is that this feature [was added a while ago](https://github.com/terraform-aws-modules/terraform-aws-alb/commit/7451e341fd4c1fb417d528fd26f1deb4eed1e9a8) but was never sent to terraform registry. The latest build for example:

https://travis-ci.org/terraform-aws-modules/terraform-aws-alb/builds/451182272

> Deploying application
> Deployment steps should include publishing to terraform registry on new releases. Exiting with success.

Is this a reminder or just a log message? Perhaps the build has to be tagged as a release to get it to push to the registry?

**Comment by uriinf** [comment] 2019-05-31 13:59
Accordingly to terraform [documentation](https://www.terraform.io/docs/providers/aws/r/lb.html#enable_cross_zone_load_balancing) it is **network load balancer feature**:
```
enable_cross_zone_load_balancing - (Optional) If true, cross-zone load balancing of the load balancer will be enabled. This is a network load balancer feature. Defaults to false. 
```

**Comment by antonbabenko** [comment] 2019-11-22 09:40
[v5.0.0](https://github.com/terraform-aws-modules/terraform-aws-alb/releases/v5.0.0) has been just released with NLB support (and more).

`enable_cross_zone_load_balancing` is a feature of NLB, as @uriinf said.

Check [UPGRADE-5.0.md](https://github.com/terraform-aws-modules/terraform-aws-alb/blob/master/UPGRADE-5.0.md) for upgrade instructions.

**Closed by antonbabenko** 2019-11-22 09:40 UTC
