### ISSUE TITLE
Error: Network Load Balancers do not support Stickiness

### ISSUE THREAD

**Issue by hemanthk85** [terraform-aws-modules/terraform-aws-alb#159] opened 2020-04-30 18:01 UTC
I am using the same settings for NLB as below and I am seeing the above mentioned error with stickiness, even after commenting out the `dynamic "stickiness"` block

Error is indicated below
```
Error: Network Load Balancers do not support Stickiness

  on modules/alb/main.tf line 54, in resource "aws_lb_target_group" "main":
  54: resource "aws_lb_target_group" "main" {


```

```
module "nlb" {
  source  = "terraform-aws-modules/alb/aws"
  version = "~> 5.0"

  name = "my-nlb"

  load_balancer_type = "network"

  vpc_id  = var.vpc_id
  subnets = var.subnet_ids

  access_logs = {
    bucket = "var.access_logs"
  }

  target_groups = [
    {
      name_prefix      = "def"
      backend_protocol = "TCP"
      backend_port     = 80
      target_type      = "ip"
    }
  ]

  http_tcp_listeners = [
    {
      port               = 80
      protocol           = "TCP"
      target_group_index = 0
    }
  ]

  tags = {
    Environment = "Test"
  }
}
```

**Comment by helmerdavila** [comment] 2020-05-07 04:40
Same here

**Comment by antonbabenko** [comment] 2020-05-07 14:31
I am trying to reproduce this one and I can't do it with the provided code.

It only fails when I specify `stickiness` argument which I see you don't specify.

```
target_groups = [
    {
      name_prefix      = "def"
      backend_protocol = "TCP"
      backend_port     = 80
      target_type      = "ip"
      stickiness = { ... } # <-- put something there
    }
  ]
```

@helmerdavila Could you verify your `target_groups` argument?

**Comment by helmerdavila** [comment] 2020-05-07 15:39
Yes, worked for me updating health checks and passing stickiness  { enabled = false  }. Should I add the docs to the NLB example?

**Comment by antonbabenko** [comment] 2020-05-08 08:09
Great,

I don't think it is necessary to add such notes to module documentation because there are dozens of arguments that can be specified in a particular combination (for ALB or for NLB). AWS documentation has it all already from their side, and `examples` directory contains the correct code already.

Closing this issue.

**Closed by antonbabenko** 2020-05-08 08:09 UTC
