### ISSUE TITLE
Invalide Attribute Combination

### ISSUE THREAD

**Issue by cdg-gavin-gavinyap** [terraform-aws-modules/terraform-aws-alb#354] opened 2024-02-20 02:20 UTC
## Description

When target group's target type is set to lambda, the following 
```
│ Warning: Invalid Attribute Combination
│ 
│   with module.lb["devops-nebula-lambda-alb-1"].aws_lb_target_group.this["lambda-target-group-0"],
│   on .terraform/modules/lb/main.tf line 485, in resource "aws_lb_target_group" "this":
│  485:   port                               = try(each.value.target_type, null) == "lambda" ? null : try(each.value.port, var.default_port)
│ 
│ Attribute "port" cannot be specified when "target_type" is "lambda".
```

- [x ] ✋ I have searched the open/closed issues and my issue is not listed.

## Versions

- Module version [Required]: 9.7.0

- Terraform version:
1.50
- Provider version(s):
.
├── provider[registry.terraform.io/hashicorp/aws]
├── module.gateway_lb
│   └── provider[registry.terraform.io/hashicorp/aws]
└── module.lb
    └── provider[registry.terraform.io/hashicorp/aws] >= 5.33.0

## Reproduction Code [Required]

  lambda-target-group-0 = {
      name_prefix                        = "l1-"
      target_type                        = "lambda"
      lambda_multi_value_headers_enabled = true
      target_id                          = module.lambda_with_allowed_triggers.lambda_function_arn
    }

1. define a ALB with target group above
2. terraform apply 

Got  the  warning in description

**Comment by bryantbiggs** [comment] 2024-03-08 17:57
we have this https://github.com/terraform-aws-modules/terraform-aws-alb/blob/eb15097ece19399858ae84518bb900bd34494a74/examples/complete-alb/main.tf#L396-L401 in our example and it works as expected

closing for now since I am not able to reproduce

**Closed by bryantbiggs** 2024-03-08 17:57 UTC
